name: CI/CD - Build and Run Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Stop existing container (if running)
      run: |
        try { docker stop node-app-container } catch { Write-Output "No container to stop" }
        try { docker rm node-app-container } catch { Write-Output "No container to remove" }
      shell: powershell
      # Fixed: Removed the period (.) at the end of lines and added explicit shell declaration

    - name: Build Docker image
      run: docker build -t node-app .

    - name: Run Docker container
      run: |
        docker run -d --name node-app-container -p 3000:3000 node-app

    - name: Verify app is running
      run: |
        Start-Sleep -Seconds 5
        Invoke-WebRequest -Uri http://localhost:3000 -UseBasicParsing | Out-Null
        Write-Output "App is running at http://localhost:3000"
      shell: powershell